/**
 * This class is generated by jOOQ
 */
package se.riges.permalink.jooq.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Permalinks extends org.jooq.impl.TableImpl<se.riges.permalink.jooq.tables.records.PermalinksRecord> {

	private static final long serialVersionUID = 1198434457;

	/**
	 * The reference instance of <code>permalinks.permalinks</code>
	 */
	public static final se.riges.permalink.jooq.tables.Permalinks PERMALINKS = new se.riges.permalink.jooq.tables.Permalinks();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<se.riges.permalink.jooq.tables.records.PermalinksRecord> getRecordType() {
		return se.riges.permalink.jooq.tables.records.PermalinksRecord.class;
	}

	/**
	 * The column <code>permalinks.permalinks.id</code>.
	 */
	public final org.jooq.TableField<se.riges.permalink.jooq.tables.records.PermalinksRecord, java.lang.Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>permalinks.permalinks.data</code>.
	 */
	public final org.jooq.TableField<se.riges.permalink.jooq.tables.records.PermalinksRecord, java.lang.String> DATA = createField("data", org.jooq.impl.SQLDataType.CLOB.length(65535), this, "");

	/**
	 * Create a <code>permalinks.permalinks</code> table reference
	 */
	public Permalinks() {
		this("permalinks", null);
	}

	/**
	 * Create an aliased <code>permalinks.permalinks</code> table reference
	 */
	public Permalinks(java.lang.String alias) {
		this(alias, se.riges.permalink.jooq.tables.Permalinks.PERMALINKS);
	}

	private Permalinks(java.lang.String alias, org.jooq.Table<se.riges.permalink.jooq.tables.records.PermalinksRecord> aliased) {
		this(alias, aliased, null);
	}

	private Permalinks(java.lang.String alias, org.jooq.Table<se.riges.permalink.jooq.tables.records.PermalinksRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, se.riges.permalink.jooq.Permalinks.PERMALINKS, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<se.riges.permalink.jooq.tables.records.PermalinksRecord, java.lang.Integer> getIdentity() {
		return se.riges.permalink.jooq.Keys.IDENTITY_PERMALINKS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<se.riges.permalink.jooq.tables.records.PermalinksRecord> getPrimaryKey() {
		return se.riges.permalink.jooq.Keys.KEY_PERMALINKS_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<se.riges.permalink.jooq.tables.records.PermalinksRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<se.riges.permalink.jooq.tables.records.PermalinksRecord>>asList(se.riges.permalink.jooq.Keys.KEY_PERMALINKS_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public se.riges.permalink.jooq.tables.Permalinks as(java.lang.String alias) {
		return new se.riges.permalink.jooq.tables.Permalinks(alias, this);
	}

	/**
	 * Rename this table
	 */
	public se.riges.permalink.jooq.tables.Permalinks rename(java.lang.String name) {
		return new se.riges.permalink.jooq.tables.Permalinks(name, null);
	}
}
