/**
 * This class is generated by jOOQ
 */
package se.riges.permalink.jooq.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PermalinksRecord extends org.jooq.impl.UpdatableRecordImpl<se.riges.permalink.jooq.tables.records.PermalinksRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 1877626515;

	/**
	 * Setter for <code>permalinks.permalinks.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>permalinks.permalinks.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>permalinks.permalinks.data</code>.
	 */
	public void setData(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>permalinks.permalinks.data</code>.
	 */
	public java.lang.String getData() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return se.riges.permalink.jooq.tables.Permalinks.PERMALINKS.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return se.riges.permalink.jooq.tables.Permalinks.PERMALINKS.DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermalinksRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermalinksRecord value2(java.lang.String value) {
		setData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public PermalinksRecord values(java.lang.Integer value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached PermalinksRecord
	 */
	public PermalinksRecord() {
		super(se.riges.permalink.jooq.tables.Permalinks.PERMALINKS);
	}

	/**
	 * Create a detached, initialised PermalinksRecord
	 */
	public PermalinksRecord(java.lang.Integer id, java.lang.String data) {
		super(se.riges.permalink.jooq.tables.Permalinks.PERMALINKS);

		setValue(0, id);
		setValue(1, data);
	}
}
