/**
 * This class is generated by jOOQ
 */
package se.riges.permalink.jooq;

/**
 * A class modelling foreign key relationships between tables of the <code>permalinks</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<se.riges.permalink.jooq.tables.records.PermalinksRecord, java.lang.Integer> IDENTITY_PERMALINKS = Identities0.IDENTITY_PERMALINKS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<se.riges.permalink.jooq.tables.records.PermalinksRecord> KEY_PERMALINKS_PRIMARY = UniqueKeys0.KEY_PERMALINKS_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<se.riges.permalink.jooq.tables.records.PermalinksRecord, java.lang.Integer> IDENTITY_PERMALINKS = createIdentity(se.riges.permalink.jooq.tables.Permalinks.PERMALINKS, se.riges.permalink.jooq.tables.Permalinks.PERMALINKS.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<se.riges.permalink.jooq.tables.records.PermalinksRecord> KEY_PERMALINKS_PRIMARY = createUniqueKey(se.riges.permalink.jooq.tables.Permalinks.PERMALINKS, se.riges.permalink.jooq.tables.Permalinks.PERMALINKS.ID);
	}
}
