/**
 * This class is generated by jOOQ
 */
package se.riges.permalink.jooq;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Permalinks extends org.jooq.impl.SchemaImpl {

	private static final long serialVersionUID = 810379056;

	/**
	 * The reference instance of <code>permalinks</code>
	 */
	public static final Permalinks PERMALINKS = new Permalinks();

	/**
	 * No further instances allowed
	 */
	private Permalinks() {
		super("permalinks");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			se.riges.permalink.jooq.tables.Permalinks.PERMALINKS);
	}
}
