/**
 * This class is generated by jOOQ
 */
package se.riges.permalink.jooq;

/**
 * Convenience access to all tables in permalinks
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table permalinks.permalinks
	 */
	public static final se.riges.permalink.jooq.tables.Permalinks PERMALINKS = se.riges.permalink.jooq.tables.Permalinks.PERMALINKS;
}
